replicaCount: 2
image:
  repository: dan1993/billing-service
  tag: dev-latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
affinity: {}

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: billing.freelas.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
