---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "client-service.fullname" . }}
  labels:
    app: {{ include "client-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "client-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "client-service.name" . }}
    spec:
      containers:
        - name: {{ include "client-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          affinity:
          {{ toYaml .Values.affinity | indent 8 }}