apiVersion: v1
kind: Service
metadata:
  name: {{ include "client-service.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ include "client-service.name" . }}