replicaCount: 2
image:
  repository: dan1993/provider-service
  tag: v1
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
affinity: {}
env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://postgresql-service:5432/provider
  - name: SPRING_DATASOURCE_USERNAME
    value: admin
  - name: SPRING_DATASOURCE_PASSWORD
    value: admin
# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: provider.freelas.dev
      paths:
        - path: /
          pathType: Prefix
  tls: []
