server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: provider-service
          uri: http://localhost:8081
          predicates:
            - Path=/providers/**

        - id: request-service
          uri: http://localhost:8082
          predicates:
            - Path=/requests/**

        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/notifications/**

        - id: client-service
          uri: http://localhost:8085
          predicates:
            - Path=/clients/**

        - id: billing-service
          uri: http://localhost:8086
          predicates:
            - Path=/billing/**

      default-filters:
        - AddResponseHeader=X-Gateway, Freelas-Gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
