replicaCount: 2
image:
  repository: dan1993/client-service
  tag: v2
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
affinity: {}
env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://postgresql-0.freelas.svc.cluster.local:5432/freelasdb
  - name: SPRING_DATASOURCE_USERNAME
    value: freelas
  - name: SPRING_DATASOURCE_PASSWORD
    value: freelas123
  - name: SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA
    value: freelasdb

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: client.freelas.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
