replicaCount: 2
image:
  repository: dan1993/client-service
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
affinity: {}
env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://postgresql-service:5432/client
  - name: SPRING_DATASOURCE_USERNAME
    value: admin
  - name: SPRING_DATASOURCE_PASSWORD
    value: admin
