replicaCount: 2
image:
  repository: dan1993/request-service
  tag: v1
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
affinity: {}
env:
  - name: SPRING_DATASOURCE_URL
    value: jdbcjdbc:postgresql://postgresql-service.freelas.svc.cluster.local:5432/requestdb
  - name: SPRING_DATASOURCE_USERNAME
    value: admin
  - name: SPRING_DATASOURCE_PASSWORD
    value: admin
  - name: SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA
    value: request
# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: request.freelas.dev
      paths:
        - path: /
          pathType: Prefix
  tls: []
