server:
  port: 8080

spring:
  application:
    name: gateway-service
  
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  cloud:
    gateway:
      routes:
        - id: provider-service
          uri: ${PROVIDER_SERVICE_URL:http://provider-service:8081}
          predicates:
            - Path=/providers/**

        - id: request-service
          uri: ${REQUEST_SERVICE_URL:http://request-service:8082}
          predicates:
            - Path=/requests/**

        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://notification-service:8084}
          predicates:
            - Path=/notifications/**

        - id: client-service
          uri: ${CLIENT_SERVICE_URL:http://client-service:8085}
          predicates:
            - Path=/clients/**

        - id: billing-service
          uri: ${BILLING_SERVICE_URL:http://billing-service:8086}
          predicates:
            - Path=/billing/**

      default-filters:
        - AddResponseHeader=X-Gateway, Freelas-Gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
