server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://postgresql-service.freelas.svc.cluster.local:5432/client
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
