server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://postgresql-service.freelas.svc.cluster.local:5432/freelasdb
    username: freelas
    password: freelas123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_schema: client
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
