server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgresql-service.freelas.svc.cluster.local:5432/clientdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_schema: provider
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers: localhost:9092
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
