name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and test microservices
        shell: bash
        run: |
          for dir in micro-services/*-service; do
            mvn -f "$dir/pom.xml" -B -ntp test
          done
      - name: Package microservices
        shell: bash
        run: |
          for dir in micro-services/*-service; do
            mvn -f "$dir/pom.xml" -B -ntp package -DskipTests
          done

  terraform:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform -chdir=terraform init
      - name: Terraform Validate
        run: terraform -chdir=terraform validate
      - name: Terraform Plan
        run: terraform -chdir=terraform plan -out=tfplan
      - name: Upload plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: terraform/tfplan
